# Generated by Django 5.1 on 2024-08-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=302)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('city', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=10)),
                ('class_student', models.CharField(max_length=30)),
                ('register_number', models.CharField(max_length=30)),
            ],
        ),
    ]
